In [27]:
import pandas as pd

In [19]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding= 'latin1', sep=';')
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [20]:
df.tail()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37994,159,6,2026,2026m06,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,0.0,0.0,18,1,0,0,0,0,158,2
37995,165,6,2026,2026m06,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,49,2,1,0,0,0,202,2
37996,166,6,2026,2026m06,33,5,Angra dos Reis,3300100,Interior,1,...,14.0,0.0,81,8,0,0,0,0,641,2
37997,167,6,2026,2026m06,43,5,Paraty,3303807,Interior,1,...,4.0,0.0,14,1,1,0,0,0,198,2
37998,168,6,2026,2026m06,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,0,0,0,0,0,32,2

In [21]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [22]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,3.799900e+04,37999.000000,37999.000000,37999.000000,37999.000000,...,33353.000000,33353.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000
mean,81.724887,6.437485,2014.401642,20.158952,3.869918,3.791066e+06,2.901155,0.028264,0.094476,3.023895,...,8.724582,0.646569,41.445959,3.238664,0.359509,0.022816,0.013211,0.002211,447.112792,2.989184
std,48.320882,3.451510,6.750784,11.353647,2.011363,1.739697e+06,4.304049,0.180037,0.364154,4.418595,...,14.692666,1.640221,39.520032,4.170925,0.983036,0.180298,0.129919,0.049156,401.757025,0.103438
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2009.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,372.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,668.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [36]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular', ascending = False)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [47]:
df_apr_menor_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_apr_menor_dp = df_apr_menor_dp.sort_values(by='aaapai', ascending = False)
df_apr_menor_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [50]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]