In [3]:
import pandas as pd
import numpy as np

In [11]:
df_canais = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/canais_venda.csv', sep=';', decimal=',')
df_canais

   id_canal    nome_canal comissao_pct
0         1  Site Próprio           8%
1         2           ota          18%
2         3      Telefone           5%
3         4       agencia          12%

In [13]:
df_clientes = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/clientes.csv', sep=';', decimal=',')
df_clientes

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física
...,...,...,...,...,...,...
296,297,Roberta Leite,Curitiba,DF,56-65,pessoa fisica
297,298,Eduardo Lopes,São Paulo,ES,36-45,PJ
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [14]:
df_funcionarios = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/funcionarios.csv', sep=';', decimal=',')
df_funcionarios

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

In [15]:
df_reserva = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/reservas.csv', sep=';', decimal=',')
df_reserva

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,confirmada,Cartão de Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,concluída,PIX
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,concluída,Cartão de Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,cancelada,PIX
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,confirmada,Cartão de Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,confirmada,PIX
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,confirmada,Transferência
2455,2456,8,4,176,1.0,2023-05-10,2023-05-17,7,1,6.0,concluída,Cartão de Débito
2456,2457,6,3,160,1.0,2023-07-01,2023-07-05,4,1,9.0,confirmada,Cartão de Crédito

In [16]:
df_quarto = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/tipos_quarto.csv', sep=';', decimal=',')
df_quarto

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      STANDARD               2         R$ 280,00
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

In [25]:
df_unidades = pd.read_csv('C:/Users/daniel.cnunes.SENACRJEDU/Documents/NaraHoteis/unidades.csv', sep=';')
df_unidades

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3 estrelas,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0