In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv('pedidos_narashop.csv', encoding= 'latin1', sep=';')
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,EletrÃ´nicos,SSD Externo,Entregue,4,599.89,8
2,10003,FlÃ¡via Azevedo,EletrÃ´nicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa TÃ©rmica,Entregue,1,87.67,4
4,10005,VinÃ­cius Lopes,EletrÃ´nicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e DecoraÃ§Ã£o,Tapete Sala,Em trÃ¢nsito,4,166.27,5
19997,29998,PatrÃ­cia Rocha,EletrÃ´nicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e DecoraÃ§Ã£o,Quadro Decorativo,Em trÃ¢nsito,3,65.70,18

In [52]:
df['valor_pedido'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,EletrÃ´nicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,FlÃ¡via Azevedo,EletrÃ´nicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa TÃ©rmica,Entregue,1,87.67,4,87.67
4,10005,VinÃ­cius Lopes,EletrÃ´nicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e DecoraÃ§Ã£o,Tapete Sala,Em trÃ¢nsito,4,166.27,5,665.08
19997,29998,PatrÃ­cia Rocha,EletrÃ´nicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e DecoraÃ§Ã£o,Quadro Decorativo,Em trÃ¢nsito,3,65.70,18,197.10

In [53]:
df_valor_pedido = df.groupby('categoria')['valor_pedido'].sum().reset_index()
df_valor_pedido = df_valor_pedido.sort_values(by='valor_pedido', ascending=False)
df_valor_pedido.head()

            categoria  valor_pedido
2        EletrÃ´nicos   37037997.65
3            Esportes    8058234.35
1  Casa e DecoraÃ§Ã£o    3333395.06
0          Brinquedos    2306126.65

In [56]:
df_3 = df.loc[(df['status_pedido'] == 'Entregue' & (df['valor_pedido'] > 500))]
df_3

TypeError: Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]

In [61]:
df_produto_valor_vendido = df.groupby('produto')['valor_pedido'].sum().reset_index()

array_valor_vendido = np.array(df_produto_valor_vendido['valor_pedido'])
array_valor_vendido

media = np.mean(array_valor_vendido)
mediana = np.median(array_valor_vendido)
q1_valor = np.percentile(array_valor_vendido, 25)
q2_valor = np.percentile(array_valor_vendido, 50)
q3_valor = np.percentile(array_valor_vendido, 75)
array_round = round(((media - mediana) / mediana) * 100,2)

top_menos_25_produto = df_produto_valor_vendido.loc[df_produto_valor_vendido['valor_pedido'] > 3]
top_menos_25_produto.sort_values(by='valor_pedido')

                        produto  valor_pedido
24          Massinha de Modelar      17550.06
9                Corda de Pular      23767.20
32               Porta-Retratos      26224.38
28       Organizador de Gavetas      36586.33
42               Tapete de Yoga      50209.91
30                     PelÃºcia      51088.67
34   Quebra-CabeÃ§a 1000 peÃ§as      51701.41
10            Difusor de Aromas      57532.21
14             Garrafa TÃ©rmica      63532.51
6          Carregador PortÃ¡til      64156.00
8           Conjunto de Toalhas      70889.32
0             Bermuda Esportiva      73266.61
18            Jogo de Tabuleiro      74070.26
26                Mouse Sem Fio      74555.56
2               Bola de Futebol      77586.08
33            Quadro Decorativo      83236.49
3             Boneca Articulada      93768.20
22           LuminÃ¡ria de Mesa     189885.38
25      Mochila de HidrataÃ§Ã£o     192107.97
31           Pista de Carrinhos     195027.74
20             Kit de CiÃªncias     196385.59
23                 Luva de Boxe     200234.01
15                     Halteres     200280.49
16                 Jogo de Cama     224794.69
29                       Patins     233110.80
35      Raquete de Beach Tennis     259327.03
12               Fone Bluetooth     264563.70
41                  Tapete Sala     264729.81
19                   Kettlebell     271850.88
11            Espelho de Parede     276184.73
7   Carrinho de Controle Remoto     277410.42
47                       Webcam     278877.33
5        Caixa de Som Bluetooth     287378.44
46             ViolÃ£o Infantil     340633.78
4           Cafeteira ElÃ©trica     362150.99
21               LEGO ClÃ¡ssico     365791.62
43            Teclado MecÃ¢nico     372827.72
44         TelescÃ³pio Infantil     409588.10
45            TÃªnis de Corrida     696912.40
36                  SSD Externo     719921.59
17              Jogo de Panelas     760544.58
13         Fritadeira Air Fryer     980636.15
39                   Smartwatch    1344856.80
40                       Tablet    3258725.63
1        Bicicleta ErgomÃ©trica    5949159.26
38                   Smartphone    6806241.19
37                     Smart TV    8474171.95
27                     Notebook   15091721.74

In [ ]:
df_produto_valor_vendido = df.groupby('produto')['valor_pedido'].sum().reset_index()

array_valor_vendido = np.array(df_produto_valor_vendido['valor_pedido'])
array_valor_vendido

media = np.mean(array_valor_vendido)
mediana = np.median(array_valor_vendido)
q1_valor = np.percentile(array_valor_vendido, 25)
q2_valor = np.percentile(array_valor_vendido, 50)
q3_valor = np.percentile(array_valor_vendido, 75)
array_round = round(((media - mediana) / mediana) * 100,2)

top_menos_25_produto = df_produto_valor_vendido.loc[df_produto_valor_vendido['valor_pedido'] > 3]
top_menos_25_produto.sort_values(by='valor_pedido')

In [65]:
array_total = np.array(df['valor_pedido'])
media_total = np.mean(array_total)
mediana_total = np.median(array_total)
dist = (media_total - mediana_total) / mediana_total
distancia_total = round(((media_total - mediana_total) / mediana_total) * 100,2)

print(f'Média total {media_total}')
print(f'Mediana total {mediana_total}')
print(f'A distância entre a média e a mediana é de {distancia_total}%')

print(dist)
print(f'{dist:.2%}')

Média total 2536.7876855
Mediana total 882.635
A distância entre a média e a mediana é de 187.41%
1.8741072872705025
187.41%

In [74]:
array_valor_vendido = np.array(df_produto_valor_vendido['valor_pedido'])

q1_valor = np.percentile(array_valor_vendido, 25)
q3_valor = np.percentile(array_valor_vendido, 75)
iqr = q3_valor - q1_valor
limite_superior = q3_valor + (1.5 * iqr)
limite_inferior = q1_valor - (1.5 * iqr)

outlier_sup = df_produto_valor_vendido.query("valor_pedido > @limite_superior")
outlier_inf = df_produto_valor_vendido.query("valor_pedido < @limite_inferior")
outlier_sup = outlier_sup.sort_values(by='valor_pedido', ascending=False)
outlier_inf = outlier_inf.sort_values(by='valor_pedido', ascending=True)

display(outlier_sup)
display(outlier_sup)

                   produto  valor_pedido
27                Notebook   15091721.74
37                Smart TV    8474171.95
38              Smartphone    6806241.19
1   Bicicleta ErgomÃ©trica    5949159.26
40                  Tablet    3258725.63
39              Smartwatch    1344856.80
13    Fritadeira Air Fryer     980636.15

                   produto  valor_pedido
27                Notebook   15091721.74
37                Smart TV    8474171.95
38              Smartphone    6806241.19
1   Bicicleta ErgomÃ©trica    5949159.26
40                  Tablet    3258725.63
39              Smartwatch    1344856.80
13    Fritadeira Air Fryer     980636.15

In [81]:
df_vendedor = df.groupby('vendedor')['valor_pedido'].sum().reset_index().sort_values(by='valor_pedido', ascending=False)
array_vendedor = np.array(df['vendedor'])

q1_vendedor = np.percentile(array_vendedor, 25)
q3_vendedor = np.percentile(array_vendedor, 75)
iqr = q3_vendedor - q1_vendedor
limite_superior = q3_vendedor + (1.5 * iqr)
limite_inferior = q1_vendedor - (1.5 * iqr)

outlier_sup = df_vendedor.query("valor_pedido > @limite_superior")
outlier_inf = df_vendedor.query("valor_pedido < @limite_inferior")
outlier_sup = outlier_sup.sort_values(by='valor_pedido', ascending=False)
outlier_inf = outlier_inf.sort_values(by='valor_pedido', ascending=True)

display(outlier_sup)
display(outlier_sup)

TypeError: unsupported operand type(s) for -: 'str' and 'str'